language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm run build
before_deploy:
  if ! [[ $TRAVIS_TAG ]]; then
    export TRAVIS_TAG="1.$TRAVIS_BUILD_NUMBER" &&
    git config --local user.name "$USER_NAME" &&
    git config --local user.email "$USER_EMAIL" &&
    git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT";
  fi
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "dist"
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    tags: true
after_deploy: "echo 'Deploy done!'"
