language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm run build
before_deploy: "echo 'Ready?'"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "dist"
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    tags: true
after_deploy: "echo 'Deploy done!'"